name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v4
      - name: Install dependencies
        run: mise run install
      - name: Test
        run: mise run test
      - name: Lint
        run: mise run lint
